apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
  namespace: kubernetes-cluster-ishangaurav
  labels:
    app: nodejs-app
spec:
  template:
    metadata:
      name: nodejs-app-pod
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: ishangaurav/i-ishangaurav-master:latest
          imagePullPolicy: Always
          ports: 
            - containerPort: 7100
              protocol: TCP
          resources:
            requests:
              memory: 250Mi
              cpu: 250m
            limits:
              memory: 500Mi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: configuration-variables
            - secretRef:
                name: secret-variable
  replicas: 4
  selector:
    matchLabels:
      app: nodejs-app