apiVersion: v1
kind: Service
metadata:
 name: nodejs-app-loadbalancer-service
 namespace: kubernetes-cluster-ishangaurav
spec:
 type: LoadBalancer
 ports:
 - targetPort: 7100
   port: 7100
   nodePort: 30081
   protocol: TCP
 selector:
  app: nodejs-app